### PR TITLE
Upgrade to TF 0.12

### PR DESCRIPTION
**Pull request by stefansedich**
Upgrading to TF 0.12, I also added a .gitignore as there was not one which caused me originally to commit the .terraform folder, this should avoid that going forward.

### CODE REVIEW

**Comment by RulerOf** [comment]
I’m open to suggestions on how to handle simultaneous compatibility for >=.12 and <.12

Are you aware of any reference for how that’s being done with other modules? It would save me some research later.

**Comment by stefansedich** [comment]
@RulerOf most modules I am dealing with have simply been bumping the major version and going with breaking changes, and if required maintaining a TF 0.11 branch.

One thing missing with this module is tagging releases, perhaps we could tag 1.0 being the supported 0.11 version, then merge TF 0.12 support in and bump the verison to 2.0, maintaining a branch for 0.11 if required and going forward focusing on 0.12 support.

**Comment by stefansedich** [comment]
@RulerOf check out https://github.com/terraform-aws-modules/terraform-aws-vpc as an example.

**Comment by stefansedich** [comment]
@RulerOf did you have any more thoughts here? BTW just rebased the PR with master after your merged the other PR lastnight.

**Comment by RulerOf** [comment]
Thanks for rebasing! I was going to comment last night after that merge,
but apparently left it before submitting.

My thoughts are that I know what I want to do, but need to spend a couple
hours putting it in place. We don’t version our internal modules in this
fashion, and I thought that version pinning didn’t work with git sources,
so if we’re just going to be providing a `?ref=` type of URL that changes
what I want to do slightly.

I may not get this exactly the way I want it until next week. I’ll drop a
note here on what I’m planning after I get a chance to spend a few minutes
on research.

**Comment by RulerOf** [comment]
>I’ll drop a note here on what I’m planning after I get a chance to spend a few minutes on research.

@stefansedich just a note now that I've taken a minute to look at it.  I'll create a branch called `dot11` that maintains .11 compatibility, update `master` for .12, and then tag each .11-compatible release with a `v1.x` tag and each .12-compatible release with a `v2.x` tag.

.12-compatible can then be accessed with the repo URL, and .11 or a specific version can be grabbed with `?ref=dot11` or `?ref=vX.Y`.

I'll push the readme changes here and then into master after I get the dot11 branch up.  I'll take care of that next week.

**Comment by stefansedich** [comment]
Sounds like a plan! thanks @RulerOf

**Comment by stefansedich** [comment]
Happy Monay @RulerOf!

Have you had a chance to look into this one at all?

**Comment by stefansedich** [comment]
Any luck getting to this one @RulerOf?

**Comment by RulerOf** [comment]
@stefansedich _finally_ got this done. A few more changes coming in today as I'm adding the functionality my company needs to consume this published version of the module instead of maintaining a private fork.

I've been running the dot12 upgrade on my own terraform projects all week and finally got to the one that depends on this. My apologies for the long delay.

Edit: Those changes are live now. You can view the PR in #4

**Pull request merged**
