### PR TITLE
Feature/instance name

### PR DESCRIPTION
**Pull request by bradleyboveinis**
Adds the name tag to the ec2 instance so that it displays in the AWS UI.

### CODE REVIEW

**Comment by ghost** [comment]
Please add the following code to server.tf. The scanner will not link to the tenable portal unless there is an EIP associated to it per the documentation.

```
resource "aws_eip" "nessus-scanner-eip" {
  vpc      = true
  instance = "${aws_instance.nessus-scanner.id}"
  tags {
      Name = "${var.scanner_name}_EIP"
  }
}

**Comment by bradleyboveinis** [comment]
thanks @iscmtyson, I have updated the PR with the code you provided, tested it, and it appears to configure the eip correctly. Thanks.

**Comment by RulerOf** [comment]
> Please add the following code to server.tf. The scanner will not link to the tenable portal unless there is an EIP associated to it per the documentation.

I checked [the documentation](https://docs.tenable.com/other/TenableioAWSIntegrationGuide.pdf) but can't find any reference to this requirement, and I can confirm that my own scanners are running behind AWS NAT inside of my VPCs without any problems. That makes this sound more like a border firewall issue and the EIP is a convenient way to bypass it.

If that's the case, I would recommend a variable that connects back to the [`associate_public_ip_address`](https://www.terraform.io/docs/providers/aws/r/instance.html#associate_public_ip_address) argument on [the `aws_instance` resource](https://github.com/BuyerQuest/terraform-tenable-nessus-scanner-aws/blob/5ff560c086137f54b6a399cca4ae19df89d43cf6/server.tf#L25) that defaults to `false`.

**Comment by bradleyboveinis** [comment]
@RulerOf at the top of page 13 and a few other pages there's a note stating "Note: You must use an Elastic IP address for the scanner to work properly." 

There isn't mention elsewhere as to why it's required, which isn't very helpful, but the wording does imply it's required for all features to work.

**Comment by stefansedich** [comment]
Any movement on this one? can we perhaps leave the `nessus-scanner-eip` change out of this PR and simply address the ability to set the name?

**Comment by RulerOf** [comment]
@stefansedich I thought I'd be able to take some time out during a workday to push the changes I needed to this branch but I just haven't worked it in and should have by now. I'll get this merged tonight.

**Comment by stefansedich** [comment]
Thanks @RulerOf I have also opened up a PR to upgrade to TF 0.12, let me know if there is anything I can do to help get these in.

**Comment by RulerOf** [comment]
@bradleyboveinis and @iscmtyson, I've made a few changes and merged this PR.  Thanks for your patience on this and for the code.

I've made a few changes to the names of the IAM and Security Group resources created behind the scenes. You'll see those changes when you update your modules.

**Pull request merged**
